insert into Dias values('Domingo')
insert into Dias values('Lunes')
insert into Dias values('Martes')
insert into Dias values('Miercoles')
insert into Dias values('Jueves')
insert into Dias values('Viernes')
insert into Dias values('Sabado')
insert into Dias values('Feriado')